# Generated by Django 5.2.3 on 2025-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='selected_option',
            field=models.IntegerField(null=True),
        ),
    ]
