# Generated by Django 5.2.3 on 2025-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='confirm_password',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='full_name',
            new_name='username',
        ),
    ]
