# Generated by Django 5.2.3 on 2025-06-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_confirm_password_userdata_confirmpassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
