# Generated by Django 5.2.3 on 2025-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_totalparticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
